/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
  java
  id("io.papermc.paperweight.userdev") version "1.5.5"
  id("xyz.jpenilla.run-paper") version "2.1.0"
}

group = "ghost3.mcplugins.customplugin"
version = "0.3.0"

java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(17))
  }
}

repositories {
  mavenCentral()
}

dependencies {
  paperweight.paperDevBundle("1.20.1-R0.1-SNAPSHOT")
  testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")
}

tasks {
  build {
    dependsOn(reobfJar)
  }

  test {
    useJUnitPlatform()
  }

  processResources {
    filteringCharset = "UTF-8"
    val projectData = mapOf(
      "name" to project.properties["name"],
      "version" to project.properties["version"]
    )
    filesMatching("plugin.yml") {
      expand(projectData)
    }
  }
}
