/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghosti3.mcplugin.customplugin;

import java.util.logging.Logger;

import org.bukkit.plugin.PluginLogger;
import org.bukkit.plugin.java.JavaPlugin;

public class CustomPlugin extends JavaPlugin {
  public static Logger plLogger = PluginLogger.getLogger("CustomPlugin");

  @Override
  public void onEnable() {
    plLogger.info("Registering custom events");
    getServer().getPluginManager().registerEvents(new CustomEventListener(), this);
  }

  @Override
  public void onDisable() {}
}
